spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.164.209:3306/xling?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

    username: root
    password: 123456
#时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

server:
  port: 8091

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.weappdemo.bean

wechat:
  appId: wx1ec7f93c422b317b
  secret: 9bbe8d696f08b6978aecf2ee617a6d26
